package com.jusbilee.app.mybatis.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserStageActLogCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public UserStageActLogCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Long value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Long value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Long value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Long> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdIsNull() {
            addCriterion("stage_song_id is null");
            return (Criteria) this;
        }

        public Criteria andStageSongIdIsNotNull() {
            addCriterion("stage_song_id is not null");
            return (Criteria) this;
        }

        public Criteria andStageSongIdEqualTo(Integer value) {
            addCriterion("stage_song_id =", value, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdNotEqualTo(Integer value) {
            addCriterion("stage_song_id <>", value, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdGreaterThan(Integer value) {
            addCriterion("stage_song_id >", value, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("stage_song_id >=", value, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdLessThan(Integer value) {
            addCriterion("stage_song_id <", value, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdLessThanOrEqualTo(Integer value) {
            addCriterion("stage_song_id <=", value, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdIn(List<Integer> values) {
            addCriterion("stage_song_id in", values, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdNotIn(List<Integer> values) {
            addCriterion("stage_song_id not in", values, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdBetween(Integer value1, Integer value2) {
            addCriterion("stage_song_id between", value1, value2, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andStageSongIdNotBetween(Integer value1, Integer value2) {
            addCriterion("stage_song_id not between", value1, value2, "stageSongId");
            return (Criteria) this;
        }

        public Criteria andIsAssistIsNull() {
            addCriterion("is_assist is null");
            return (Criteria) this;
        }

        public Criteria andIsAssistIsNotNull() {
            addCriterion("is_assist is not null");
            return (Criteria) this;
        }

        public Criteria andIsAssistEqualTo(Byte value) {
            addCriterion("is_assist =", value, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistNotEqualTo(Byte value) {
            addCriterion("is_assist <>", value, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistGreaterThan(Byte value) {
            addCriterion("is_assist >", value, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_assist >=", value, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistLessThan(Byte value) {
            addCriterion("is_assist <", value, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistLessThanOrEqualTo(Byte value) {
            addCriterion("is_assist <=", value, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistIn(List<Byte> values) {
            addCriterion("is_assist in", values, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistNotIn(List<Byte> values) {
            addCriterion("is_assist not in", values, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistBetween(Byte value1, Byte value2) {
            addCriterion("is_assist between", value1, value2, "isAssist");
            return (Criteria) this;
        }

        public Criteria andIsAssistNotBetween(Byte value1, Byte value2) {
            addCriterion("is_assist not between", value1, value2, "isAssist");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdIsNull() {
            addCriterion("assist_user_id is null");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdIsNotNull() {
            addCriterion("assist_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdEqualTo(Long value) {
            addCriterion("assist_user_id =", value, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdNotEqualTo(Long value) {
            addCriterion("assist_user_id <>", value, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdGreaterThan(Long value) {
            addCriterion("assist_user_id >", value, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("assist_user_id >=", value, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdLessThan(Long value) {
            addCriterion("assist_user_id <", value, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdLessThanOrEqualTo(Long value) {
            addCriterion("assist_user_id <=", value, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdIn(List<Long> values) {
            addCriterion("assist_user_id in", values, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdNotIn(List<Long> values) {
            addCriterion("assist_user_id not in", values, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdBetween(Long value1, Long value2) {
            addCriterion("assist_user_id between", value1, value2, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andAssistUserIdNotBetween(Long value1, Long value2) {
            addCriterion("assist_user_id not between", value1, value2, "assistUserId");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(Integer value1, Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andIsPassedIsNull() {
            addCriterion("is_passed is null");
            return (Criteria) this;
        }

        public Criteria andIsPassedIsNotNull() {
            addCriterion("is_passed is not null");
            return (Criteria) this;
        }

        public Criteria andIsPassedEqualTo(Byte value) {
            addCriterion("is_passed =", value, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedNotEqualTo(Byte value) {
            addCriterion("is_passed <>", value, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedGreaterThan(Byte value) {
            addCriterion("is_passed >", value, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_passed >=", value, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedLessThan(Byte value) {
            addCriterion("is_passed <", value, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedLessThanOrEqualTo(Byte value) {
            addCriterion("is_passed <=", value, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedIn(List<Byte> values) {
            addCriterion("is_passed in", values, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedNotIn(List<Byte> values) {
            addCriterion("is_passed not in", values, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedBetween(Byte value1, Byte value2) {
            addCriterion("is_passed between", value1, value2, "isPassed");
            return (Criteria) this;
        }

        public Criteria andIsPassedNotBetween(Byte value1, Byte value2) {
            addCriterion("is_passed not between", value1, value2, "isPassed");
            return (Criteria) this;
        }

        public Criteria andActCountIsNull() {
            addCriterion("act_count is null");
            return (Criteria) this;
        }

        public Criteria andActCountIsNotNull() {
            addCriterion("act_count is not null");
            return (Criteria) this;
        }

        public Criteria andActCountEqualTo(Integer value) {
            addCriterion("act_count =", value, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountNotEqualTo(Integer value) {
            addCriterion("act_count <>", value, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountGreaterThan(Integer value) {
            addCriterion("act_count >", value, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("act_count >=", value, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountLessThan(Integer value) {
            addCriterion("act_count <", value, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountLessThanOrEqualTo(Integer value) {
            addCriterion("act_count <=", value, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountIn(List<Integer> values) {
            addCriterion("act_count in", values, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountNotIn(List<Integer> values) {
            addCriterion("act_count not in", values, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountBetween(Integer value1, Integer value2) {
            addCriterion("act_count between", value1, value2, "actCount");
            return (Criteria) this;
        }

        public Criteria andActCountNotBetween(Integer value1, Integer value2) {
            addCriterion("act_count not between", value1, value2, "actCount");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Byte value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Byte value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Byte value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Byte value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Byte value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Byte> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Byte> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Byte value1, Byte value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 24 21:12:33 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_user_stage_act_log
     *
     * @mbg.generated Wed Aug 24 21:12:33 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}