package com.jusbilee.app.mybatis.pojo;

import java.util.Date;

public class UserSummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.id
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.user_id
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.total_gold_coin
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer totalGoldCoin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.total_practice_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer totalPracticeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.total_practice_score
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer totalPracticeScore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.total_practice_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer totalPracticeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.unlock_practice_song_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer unlockPracticeSongCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.match_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer matchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.match_win_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Integer matchWinCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.last_practice_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Date lastPracticeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.create_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_summary.update_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.id
     *
     * @return the value of t_user_summary.id
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.id
     *
     * @param id the value for t_user_summary.id
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.user_id
     *
     * @return the value of t_user_summary.user_id
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.user_id
     *
     * @param userId the value for t_user_summary.user_id
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.total_gold_coin
     *
     * @return the value of t_user_summary.total_gold_coin
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getTotalGoldCoin() {
        return totalGoldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.total_gold_coin
     *
     * @param totalGoldCoin the value for t_user_summary.total_gold_coin
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setTotalGoldCoin(Integer totalGoldCoin) {
        this.totalGoldCoin = totalGoldCoin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.total_practice_time
     *
     * @return the value of t_user_summary.total_practice_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getTotalPracticeTime() {
        return totalPracticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.total_practice_time
     *
     * @param totalPracticeTime the value for t_user_summary.total_practice_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setTotalPracticeTime(Integer totalPracticeTime) {
        this.totalPracticeTime = totalPracticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.total_practice_score
     *
     * @return the value of t_user_summary.total_practice_score
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getTotalPracticeScore() {
        return totalPracticeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.total_practice_score
     *
     * @param totalPracticeScore the value for t_user_summary.total_practice_score
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setTotalPracticeScore(Integer totalPracticeScore) {
        this.totalPracticeScore = totalPracticeScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.total_practice_count
     *
     * @return the value of t_user_summary.total_practice_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getTotalPracticeCount() {
        return totalPracticeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.total_practice_count
     *
     * @param totalPracticeCount the value for t_user_summary.total_practice_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setTotalPracticeCount(Integer totalPracticeCount) {
        this.totalPracticeCount = totalPracticeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.unlock_practice_song_count
     *
     * @return the value of t_user_summary.unlock_practice_song_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getUnlockPracticeSongCount() {
        return unlockPracticeSongCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.unlock_practice_song_count
     *
     * @param unlockPracticeSongCount the value for t_user_summary.unlock_practice_song_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setUnlockPracticeSongCount(Integer unlockPracticeSongCount) {
        this.unlockPracticeSongCount = unlockPracticeSongCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.match_count
     *
     * @return the value of t_user_summary.match_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getMatchCount() {
        return matchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.match_count
     *
     * @param matchCount the value for t_user_summary.match_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setMatchCount(Integer matchCount) {
        this.matchCount = matchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.match_win_count
     *
     * @return the value of t_user_summary.match_win_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Integer getMatchWinCount() {
        return matchWinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.match_win_count
     *
     * @param matchWinCount the value for t_user_summary.match_win_count
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setMatchWinCount(Integer matchWinCount) {
        this.matchWinCount = matchWinCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.last_practice_time
     *
     * @return the value of t_user_summary.last_practice_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Date getLastPracticeTime() {
        return lastPracticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.last_practice_time
     *
     * @param lastPracticeTime the value for t_user_summary.last_practice_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setLastPracticeTime(Date lastPracticeTime) {
        this.lastPracticeTime = lastPracticeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.create_time
     *
     * @return the value of t_user_summary.create_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.create_time
     *
     * @param createTime the value for t_user_summary.create_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_summary.update_time
     *
     * @return the value of t_user_summary.update_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_summary.update_time
     *
     * @param updateTime the value for t_user_summary.update_time
     *
     * @mbg.generated Mon Sep 05 21:07:47 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}