package com.jusbilee.app.mybatis.pojo;

import java.util.Date;

public class UserSeasonRaceSummary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.user_id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.season_id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Integer seasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.win
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Integer win;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.loss
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Integer loss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.score
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.is_deleted
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Byte isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.create_time
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_season_race_summary.update_time
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.id
     *
     * @return the value of t_user_season_race_summary.id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.id
     *
     * @param id the value for t_user_season_race_summary.id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.user_id
     *
     * @return the value of t_user_season_race_summary.user_id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.user_id
     *
     * @param userId the value for t_user_season_race_summary.user_id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.season_id
     *
     * @return the value of t_user_season_race_summary.season_id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Integer getSeasonId() {
        return seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.season_id
     *
     * @param seasonId the value for t_user_season_race_summary.season_id
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.win
     *
     * @return the value of t_user_season_race_summary.win
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Integer getWin() {
        return win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.win
     *
     * @param win the value for t_user_season_race_summary.win
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setWin(Integer win) {
        this.win = win;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.loss
     *
     * @return the value of t_user_season_race_summary.loss
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Integer getLoss() {
        return loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.loss
     *
     * @param loss the value for t_user_season_race_summary.loss
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setLoss(Integer loss) {
        this.loss = loss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.score
     *
     * @return the value of t_user_season_race_summary.score
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.score
     *
     * @param score the value for t_user_season_race_summary.score
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.is_deleted
     *
     * @return the value of t_user_season_race_summary.is_deleted
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Byte getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.is_deleted
     *
     * @param isDeleted the value for t_user_season_race_summary.is_deleted
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setIsDeleted(Byte isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.create_time
     *
     * @return the value of t_user_season_race_summary.create_time
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.create_time
     *
     * @param createTime the value for t_user_season_race_summary.create_time
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_season_race_summary.update_time
     *
     * @return the value of t_user_season_race_summary.update_time
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_season_race_summary.update_time
     *
     * @param updateTime the value for t_user_season_race_summary.update_time
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}