package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.RaceSeason;
import com.jusbilee.app.mybatis.pojo.RaceSeasonCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface RaceSeasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @SelectProvider(type=RaceSeasonSqlProvider.class, method="countByExample")
    long countByExample(RaceSeasonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @DeleteProvider(type=RaceSeasonSqlProvider.class, method="deleteByExample")
    int deleteByExample(RaceSeasonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Delete({
        "delete from t_race_season",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Insert({
        "insert into t_race_season (season_name, start_time, ",
        "end_time, is_deleted, ",
        "create_time, update_time)",
        "values (#{seasonName,jdbcType=VARCHAR}, #{startTime,jdbcType=TIMESTAMP}, ",
        "#{endTime,jdbcType=TIMESTAMP}, #{isDeleted,jdbcType=TINYINT}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(RaceSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @InsertProvider(type=RaceSeasonSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(RaceSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @SelectProvider(type=RaceSeasonSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="season_name", property="seasonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<RaceSeason> selectByExample(RaceSeasonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Select({
        "select",
        "id, season_name, start_time, end_time, is_deleted, create_time, update_time",
        "from t_race_season",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="season_name", property="seasonName", jdbcType=JdbcType.VARCHAR),
        @Result(column="start_time", property="startTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="end_time", property="endTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    RaceSeason selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @UpdateProvider(type=RaceSeasonSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") RaceSeason record, @Param("example") RaceSeasonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @UpdateProvider(type=RaceSeasonSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") RaceSeason record, @Param("example") RaceSeasonCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @UpdateProvider(type=RaceSeasonSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(RaceSeason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_race_season
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Update({
        "update t_race_season",
        "set season_name = #{seasonName,jdbcType=VARCHAR},",
          "start_time = #{startTime,jdbcType=TIMESTAMP},",
          "end_time = #{endTime,jdbcType=TIMESTAMP},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(RaceSeason record);
}