package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserStageSummary;
import com.jusbilee.app.mybatis.pojo.UserStageSummaryCriteria.Criteria;
import com.jusbilee.app.mybatis.pojo.UserStageSummaryCriteria.Criterion;
import com.jusbilee.app.mybatis.pojo.UserStageSummaryCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserStageSummarySqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String countByExample(UserStageSummaryCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_user_stage_summary");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String deleteByExample(UserStageSummaryCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_user_stage_summary");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String insertSelective(UserStageSummary record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_user_stage_summary");
        
        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }
        
        if (record.getStageSongId() != null) {
            sql.VALUES("stage_song_id", "#{stageSongId,jdbcType=INTEGER}");
        }
        
        if (record.getLevelId() != null) {
            sql.VALUES("level_id", "#{levelId,jdbcType=INTEGER}");
        }
        
        if (record.getSongId() != null) {
            sql.VALUES("song_id", "#{songId,jdbcType=INTEGER}");
        }
        
        if (record.getIsAssist() != null) {
            sql.VALUES("is_assist", "#{isAssist,jdbcType=TINYINT}");
        }
        
        if (record.getAssistUserId() != null) {
            sql.VALUES("assist_user_id", "#{assistUserId,jdbcType=BIGINT}");
        }
        
        if (record.getScore() != null) {
            sql.VALUES("score", "#{score,jdbcType=INTEGER}");
        }
        
        if (record.getIsPassed() != null) {
            sql.VALUES("is_passed", "#{isPassed,jdbcType=TINYINT}");
        }
        
        if (record.getStageCount() != null) {
            sql.VALUES("stage_count", "#{stageCount,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("update_time", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String selectByExample(UserStageSummaryCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("stage_song_id");
        sql.SELECT("level_id");
        sql.SELECT("song_id");
        sql.SELECT("is_assist");
        sql.SELECT("assist_user_id");
        sql.SELECT("score");
        sql.SELECT("is_passed");
        sql.SELECT("stage_count");
        sql.SELECT("create_time");
        sql.SELECT("update_time");
        sql.FROM("t_user_stage_summary");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
         if (example.getLimit() != null && example.getOffset() != null) {
              StringBuilder buf = new StringBuilder(128);
              sql.usingAppender(buf);
              buf.append(" limit ");
              buf.append(example.getOffset());
              buf.append(", ");
              buf.append(example.getLimit());
              return buf.toString();
             }
            return sql.toString();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserStageSummary record = (UserStageSummary) parameter.get("record");
        UserStageSummaryCriteria example = (UserStageSummaryCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_user_stage_summary");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=BIGINT}");
        }
        
        if (record.getStageSongId() != null) {
            sql.SET("stage_song_id = #{record.stageSongId,jdbcType=INTEGER}");
        }
        
        if (record.getLevelId() != null) {
            sql.SET("level_id = #{record.levelId,jdbcType=INTEGER}");
        }
        
        if (record.getSongId() != null) {
            sql.SET("song_id = #{record.songId,jdbcType=INTEGER}");
        }
        
        if (record.getIsAssist() != null) {
            sql.SET("is_assist = #{record.isAssist,jdbcType=TINYINT}");
        }
        
        if (record.getAssistUserId() != null) {
            sql.SET("assist_user_id = #{record.assistUserId,jdbcType=BIGINT}");
        }
        
        if (record.getScore() != null) {
            sql.SET("score = #{record.score,jdbcType=INTEGER}");
        }
        
        if (record.getIsPassed() != null) {
            sql.SET("is_passed = #{record.isPassed,jdbcType=TINYINT}");
        }
        
        if (record.getStageCount() != null) {
            sql.SET("stage_count = #{record.stageCount,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_user_stage_summary");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("user_id = #{record.userId,jdbcType=BIGINT}");
        sql.SET("stage_song_id = #{record.stageSongId,jdbcType=INTEGER}");
        sql.SET("level_id = #{record.levelId,jdbcType=INTEGER}");
        sql.SET("song_id = #{record.songId,jdbcType=INTEGER}");
        sql.SET("is_assist = #{record.isAssist,jdbcType=TINYINT}");
        sql.SET("assist_user_id = #{record.assistUserId,jdbcType=BIGINT}");
        sql.SET("score = #{record.score,jdbcType=INTEGER}");
        sql.SET("is_passed = #{record.isPassed,jdbcType=TINYINT}");
        sql.SET("stage_count = #{record.stageCount,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("update_time = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        UserStageSummaryCriteria example = (UserStageSummaryCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String updateByPrimaryKeySelective(UserStageSummary record) {
        SQL sql = new SQL();
        sql.UPDATE("t_user_stage_summary");
        
        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }
        
        if (record.getStageSongId() != null) {
            sql.SET("stage_song_id = #{stageSongId,jdbcType=INTEGER}");
        }
        
        if (record.getLevelId() != null) {
            sql.SET("level_id = #{levelId,jdbcType=INTEGER}");
        }
        
        if (record.getSongId() != null) {
            sql.SET("song_id = #{songId,jdbcType=INTEGER}");
        }
        
        if (record.getIsAssist() != null) {
            sql.SET("is_assist = #{isAssist,jdbcType=TINYINT}");
        }
        
        if (record.getAssistUserId() != null) {
            sql.SET("assist_user_id = #{assistUserId,jdbcType=BIGINT}");
        }
        
        if (record.getScore() != null) {
            sql.SET("score = #{score,jdbcType=INTEGER}");
        }
        
        if (record.getIsPassed() != null) {
            sql.SET("is_passed = #{isPassed,jdbcType=TINYINT}");
        }
        
        if (record.getStageCount() != null) {
            sql.SET("stage_count = #{stageCount,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("update_time = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    protected void applyWhere(SQL sql, UserStageSummaryCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}