package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserSeasonRacePool;
import com.jusbilee.app.mybatis.pojo.UserSeasonRacePoolCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserSeasonRacePoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @SelectProvider(type=UserSeasonRacePoolSqlProvider.class, method="countByExample")
    long countByExample(UserSeasonRacePoolCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @DeleteProvider(type=UserSeasonRacePoolSqlProvider.class, method="deleteByExample")
    int deleteByExample(UserSeasonRacePoolCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @Delete({
        "delete from t_user_season_race_pool",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @Insert({
        "insert into t_user_season_race_pool (user_id, opponent_id, ",
        "sub_level_id, season_song_id, ",
        "is_match)",
        "values (#{userId,jdbcType=BIGINT}, #{opponentId,jdbcType=BIGINT}, ",
        "#{subLevelId,jdbcType=INTEGER}, #{seasonSongId,jdbcType=INTEGER}, ",
        "#{isMatch,jdbcType=TINYINT})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(UserSeasonRacePool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @InsertProvider(type=UserSeasonRacePoolSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(UserSeasonRacePool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @SelectProvider(type=UserSeasonRacePoolSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="opponent_id", property="opponentId", jdbcType=JdbcType.BIGINT),
        @Result(column="sub_level_id", property="subLevelId", jdbcType=JdbcType.INTEGER),
        @Result(column="season_song_id", property="seasonSongId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_match", property="isMatch", jdbcType=JdbcType.TINYINT)
    })
    List<UserSeasonRacePool> selectByExample(UserSeasonRacePoolCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @Select({
        "select",
        "id, user_id, opponent_id, sub_level_id, season_song_id, is_match",
        "from t_user_season_race_pool",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="opponent_id", property="opponentId", jdbcType=JdbcType.BIGINT),
        @Result(column="sub_level_id", property="subLevelId", jdbcType=JdbcType.INTEGER),
        @Result(column="season_song_id", property="seasonSongId", jdbcType=JdbcType.INTEGER),
        @Result(column="is_match", property="isMatch", jdbcType=JdbcType.TINYINT)
    })
    UserSeasonRacePool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @UpdateProvider(type=UserSeasonRacePoolSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserSeasonRacePool record, @Param("example") UserSeasonRacePoolCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @UpdateProvider(type=UserSeasonRacePoolSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserSeasonRacePool record, @Param("example") UserSeasonRacePoolCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @UpdateProvider(type=UserSeasonRacePoolSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserSeasonRacePool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_pool
     *
     * @mbg.generated Sun Sep 25 00:34:55 CST 2016
     */
    @Update({
        "update t_user_season_race_pool",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "opponent_id = #{opponentId,jdbcType=BIGINT},",
          "sub_level_id = #{subLevelId,jdbcType=INTEGER},",
          "season_song_id = #{seasonSongId,jdbcType=INTEGER},",
          "is_match = #{isMatch,jdbcType=TINYINT}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserSeasonRacePool record);
}