package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserSeasonRaceLog;
import com.jusbilee.app.mybatis.pojo.UserSeasonRaceLogCriteria.Criteria;
import com.jusbilee.app.mybatis.pojo.UserSeasonRaceLogCriteria.Criterion;
import com.jusbilee.app.mybatis.pojo.UserSeasonRaceLogCriteria;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserSeasonRaceLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String countByExample(UserSeasonRaceLogCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_user_season_race_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String deleteByExample(UserSeasonRaceLogCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_user_season_race_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String insertSelective(UserSeasonRaceLog record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_user_season_race_log");
        
        if (record.getSeasonId() != null) {
            sql.VALUES("season_id", "#{seasonId,jdbcType=INTEGER}");
        }
        
        if (record.getWinnerUserId() != null) {
            sql.VALUES("winner_user_id", "#{winnerUserId,jdbcType=BIGINT}");
        }
        
        if (record.getWinnerScore() != null) {
            sql.VALUES("winner_score", "#{winnerScore,jdbcType=INTEGER}");
        }
        
        if (record.getLoserUserId() != null) {
            sql.VALUES("loser_user_id", "#{loserUserId,jdbcType=BIGINT}");
        }
        
        if (record.getLoserScore() != null) {
            sql.VALUES("loser_score", "#{loserScore,jdbcType=INTEGER}");
        }
        
        if (record.getSeasonSongId() != null) {
            sql.VALUES("season_song_id", "#{seasonSongId,jdbcType=INTEGER}");
        }
        
        if (record.getSongId() != null) {
            sql.VALUES("song_id", "#{songId,jdbcType=INTEGER}");
        }
        
        if (record.getSongLevelId() != null) {
            sql.VALUES("song_level_id", "#{songLevelId,jdbcType=INTEGER}");
        }
        
        if (record.getSongSubLevelId() != null) {
            sql.VALUES("song_sub_level_id", "#{songSubLevelId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String selectByExample(UserSeasonRaceLogCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("season_id");
        sql.SELECT("winner_user_id");
        sql.SELECT("winner_score");
        sql.SELECT("loser_user_id");
        sql.SELECT("loser_score");
        sql.SELECT("season_song_id");
        sql.SELECT("song_id");
        sql.SELECT("song_level_id");
        sql.SELECT("song_sub_level_id");
        sql.SELECT("create_time");
        sql.FROM("t_user_season_race_log");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
         if (example.getLimit() != null && example.getOffset() != null) {
              StringBuilder buf = new StringBuilder(128);
              sql.usingAppender(buf);
              buf.append(" limit ");
              buf.append(example.getOffset());
              buf.append(", ");
              buf.append(example.getLimit());
              return buf.toString();
             }
            return sql.toString();
        }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserSeasonRaceLog record = (UserSeasonRaceLog) parameter.get("record");
        UserSeasonRaceLogCriteria example = (UserSeasonRaceLogCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("t_user_season_race_log");
        
        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=INTEGER}");
        }
        
        if (record.getSeasonId() != null) {
            sql.SET("season_id = #{record.seasonId,jdbcType=INTEGER}");
        }
        
        if (record.getWinnerUserId() != null) {
            sql.SET("winner_user_id = #{record.winnerUserId,jdbcType=BIGINT}");
        }
        
        if (record.getWinnerScore() != null) {
            sql.SET("winner_score = #{record.winnerScore,jdbcType=INTEGER}");
        }
        
        if (record.getLoserUserId() != null) {
            sql.SET("loser_user_id = #{record.loserUserId,jdbcType=BIGINT}");
        }
        
        if (record.getLoserScore() != null) {
            sql.SET("loser_score = #{record.loserScore,jdbcType=INTEGER}");
        }
        
        if (record.getSeasonSongId() != null) {
            sql.SET("season_song_id = #{record.seasonSongId,jdbcType=INTEGER}");
        }
        
        if (record.getSongId() != null) {
            sql.SET("song_id = #{record.songId,jdbcType=INTEGER}");
        }
        
        if (record.getSongLevelId() != null) {
            sql.SET("song_level_id = #{record.songLevelId,jdbcType=INTEGER}");
        }
        
        if (record.getSongSubLevelId() != null) {
            sql.SET("song_sub_level_id = #{record.songSubLevelId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_user_season_race_log");
        
        sql.SET("id = #{record.id,jdbcType=INTEGER}");
        sql.SET("season_id = #{record.seasonId,jdbcType=INTEGER}");
        sql.SET("winner_user_id = #{record.winnerUserId,jdbcType=BIGINT}");
        sql.SET("winner_score = #{record.winnerScore,jdbcType=INTEGER}");
        sql.SET("loser_user_id = #{record.loserUserId,jdbcType=BIGINT}");
        sql.SET("loser_score = #{record.loserScore,jdbcType=INTEGER}");
        sql.SET("season_song_id = #{record.seasonSongId,jdbcType=INTEGER}");
        sql.SET("song_id = #{record.songId,jdbcType=INTEGER}");
        sql.SET("song_level_id = #{record.songLevelId,jdbcType=INTEGER}");
        sql.SET("song_sub_level_id = #{record.songSubLevelId,jdbcType=INTEGER}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        
        UserSeasonRaceLogCriteria example = (UserSeasonRaceLogCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    public String updateByPrimaryKeySelective(UserSeasonRaceLog record) {
        SQL sql = new SQL();
        sql.UPDATE("t_user_season_race_log");
        
        if (record.getSeasonId() != null) {
            sql.SET("season_id = #{seasonId,jdbcType=INTEGER}");
        }
        
        if (record.getWinnerUserId() != null) {
            sql.SET("winner_user_id = #{winnerUserId,jdbcType=BIGINT}");
        }
        
        if (record.getWinnerScore() != null) {
            sql.SET("winner_score = #{winnerScore,jdbcType=INTEGER}");
        }
        
        if (record.getLoserUserId() != null) {
            sql.SET("loser_user_id = #{loserUserId,jdbcType=BIGINT}");
        }
        
        if (record.getLoserScore() != null) {
            sql.SET("loser_score = #{loserScore,jdbcType=INTEGER}");
        }
        
        if (record.getSeasonSongId() != null) {
            sql.SET("season_song_id = #{seasonSongId,jdbcType=INTEGER}");
        }
        
        if (record.getSongId() != null) {
            sql.SET("song_id = #{songId,jdbcType=INTEGER}");
        }
        
        if (record.getSongLevelId() != null) {
            sql.SET("song_level_id = #{songLevelId,jdbcType=INTEGER}");
        }
        
        if (record.getSongSubLevelId() != null) {
            sql.SET("song_sub_level_id = #{songSubLevelId,jdbcType=INTEGER}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("id = #{id,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_log
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    protected void applyWhere(SQL sql, UserSeasonRaceLogCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}