package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserPracticeSummary;
import com.jusbilee.app.mybatis.pojo.UserPracticeSummaryCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserPracticeSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @SelectProvider(type = UserPracticeSummarySqlProvider.class, method = "countByExample")
    long countByExample(UserPracticeSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @DeleteProvider(type = UserPracticeSummarySqlProvider.class, method = "deleteByExample")
    int deleteByExample(UserPracticeSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Delete({
            "delete from t_user_practice_summary",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Insert({
            "insert into t_user_practice_summary (user_id, practice_song_id, ",
            "style_id, song_id, ",
            "total_practice_time, total_practice_count, ",
            "total_practice_score, best_avg_score, ",
            "full_score_best_time, unlock_type, ",
            "create_time, update_time)",
            "values (#{userId,jdbcType=BIGINT}, #{practiceSongId,jdbcType=INTEGER}, ",
            "#{styleId,jdbcType=INTEGER}, #{songId,jdbcType=INTEGER}, ",
            "#{totalPracticeTime,jdbcType=INTEGER}, #{totalPracticeCount,jdbcType=INTEGER}, ",
            "#{totalPracticeScore,jdbcType=INTEGER}, #{bestAvgScore,jdbcType=INTEGER}, ",
            "#{fullScoreBestTime,jdbcType=INTEGER}, #{unlockType,jdbcType=INTEGER}, ",
            "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insert(UserPracticeSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @InsertProvider(type = UserPracticeSummarySqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Integer.class)
    int insertSelective(UserPracticeSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @SelectProvider(type = UserPracticeSummarySqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.BIGINT),
            @Result(column = "practice_song_id", property = "practiceSongId", jdbcType = JdbcType.INTEGER),
            @Result(column = "style_id", property = "styleId", jdbcType = JdbcType.INTEGER),
            @Result(column = "song_id", property = "songId", jdbcType = JdbcType.INTEGER),
            @Result(column = "total_practice_time", property = "totalPracticeTime", jdbcType = JdbcType.INTEGER),
            @Result(column = "total_practice_count", property = "totalPracticeCount", jdbcType = JdbcType.INTEGER),
            @Result(column = "total_practice_score", property = "totalPracticeScore", jdbcType = JdbcType.INTEGER),
            @Result(column = "best_avg_score", property = "bestAvgScore", jdbcType = JdbcType.INTEGER),
            @Result(column = "full_score_best_time", property = "fullScoreBestTime", jdbcType = JdbcType.INTEGER),
            @Result(column = "unlock_type", property = "unlockType", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "update_time", property = "updateTime", jdbcType = JdbcType.TIMESTAMP)
    })
    List<UserPracticeSummary> selectByExample(UserPracticeSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Select({
            "select",
            "id, user_id, practice_song_id, style_id, song_id, total_practice_time, total_practice_count, ",
            "total_practice_score, best_avg_score, full_score_best_time, unlock_type, create_time, ",
            "update_time",
            "from t_user_practice_summary",
            "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.INTEGER, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.BIGINT),
            @Result(column = "practice_song_id", property = "practiceSongId", jdbcType = JdbcType.INTEGER),
            @Result(column = "style_id", property = "styleId", jdbcType = JdbcType.INTEGER),
            @Result(column = "song_id", property = "songId", jdbcType = JdbcType.INTEGER),
            @Result(column = "total_practice_time", property = "totalPracticeTime", jdbcType = JdbcType.INTEGER),
            @Result(column = "total_practice_count", property = "totalPracticeCount", jdbcType = JdbcType.INTEGER),
            @Result(column = "total_practice_score", property = "totalPracticeScore", jdbcType = JdbcType.INTEGER),
            @Result(column = "best_avg_score", property = "bestAvgScore", jdbcType = JdbcType.INTEGER),
            @Result(column = "full_score_best_time", property = "fullScoreBestTime", jdbcType = JdbcType.INTEGER),
            @Result(column = "unlock_type", property = "unlockType", jdbcType = JdbcType.INTEGER),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP),
            @Result(column = "update_time", property = "updateTime", jdbcType = JdbcType.TIMESTAMP)
    })
    UserPracticeSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @UpdateProvider(type = UserPracticeSummarySqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserPracticeSummary record, @Param("example") UserPracticeSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @UpdateProvider(type = UserPracticeSummarySqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") UserPracticeSummary record, @Param("example") UserPracticeSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @UpdateProvider(type = UserPracticeSummarySqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserPracticeSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_practice_summary
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Update({
            "update t_user_practice_summary",
            "set user_id = #{userId,jdbcType=BIGINT},",
            "practice_song_id = #{practiceSongId,jdbcType=INTEGER},",
            "style_id = #{styleId,jdbcType=INTEGER},",
            "song_id = #{songId,jdbcType=INTEGER},",
            "total_practice_time = #{totalPracticeTime,jdbcType=INTEGER},",
            "total_practice_count = #{totalPracticeCount,jdbcType=INTEGER},",
            "total_practice_score = #{totalPracticeScore,jdbcType=INTEGER},",
            "best_avg_score = #{bestAvgScore,jdbcType=INTEGER},",
            "full_score_best_time = #{fullScoreBestTime,jdbcType=INTEGER},",
            "unlock_type = #{unlockType,jdbcType=INTEGER},",
            "create_time = #{createTime,jdbcType=TIMESTAMP},",
            "update_time = #{updateTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserPracticeSummary record);
}