package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserGoldCoinLog;
import com.jusbilee.app.mybatis.pojo.UserGoldCoinLogCriteria;
import org.apache.ibatis.annotations.*;
import org.apache.ibatis.type.JdbcType;

import java.util.List;

public interface UserGoldCoinLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @SelectProvider(type = UserGoldCoinLogSqlProvider.class, method = "countByExample")
    long countByExample(UserGoldCoinLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @DeleteProvider(type = UserGoldCoinLogSqlProvider.class, method = "deleteByExample")
    int deleteByExample(UserGoldCoinLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Delete({
            "delete from t_user_gold_coin_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Insert({
            "insert into t_user_gold_coin_log (user_id, type, ",
            "gold_coin, event_id, ",
            "event_name, event_target_id, ",
            "create_time)",
            "values (#{userId,jdbcType=BIGINT}, #{type,jdbcType=TINYINT}, ",
            "#{goldCoin,jdbcType=INTEGER}, #{eventId,jdbcType=INTEGER}, ",
            "#{eventName,jdbcType=VARCHAR}, #{eventTargetId,jdbcType=BIGINT}, ",
            "#{createTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insert(UserGoldCoinLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @InsertProvider(type = UserGoldCoinLogSqlProvider.class, method = "insertSelective")
    @SelectKey(statement = "SELECT LAST_INSERT_ID()", keyProperty = "id", before = false, resultType = Long.class)
    int insertSelective(UserGoldCoinLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @SelectProvider(type = UserGoldCoinLogSqlProvider.class, method = "selectByExample")
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.BIGINT),
            @Result(column = "type", property = "type", jdbcType = JdbcType.TINYINT),
            @Result(column = "gold_coin", property = "goldCoin", jdbcType = JdbcType.INTEGER),
            @Result(column = "event_id", property = "eventId", jdbcType = JdbcType.INTEGER),
            @Result(column = "event_name", property = "eventName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "event_target_id", property = "eventTargetId", jdbcType = JdbcType.BIGINT),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP)
    })
    List<UserGoldCoinLog> selectByExample(UserGoldCoinLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Select({
            "select",
            "id, user_id, type, gold_coin, event_id, event_name, event_target_id, create_time",
            "from t_user_gold_coin_log",
            "where id = #{id,jdbcType=BIGINT}"
    })
    @Results({
            @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
            @Result(column = "user_id", property = "userId", jdbcType = JdbcType.BIGINT),
            @Result(column = "type", property = "type", jdbcType = JdbcType.TINYINT),
            @Result(column = "gold_coin", property = "goldCoin", jdbcType = JdbcType.INTEGER),
            @Result(column = "event_id", property = "eventId", jdbcType = JdbcType.INTEGER),
            @Result(column = "event_name", property = "eventName", jdbcType = JdbcType.VARCHAR),
            @Result(column = "event_target_id", property = "eventTargetId", jdbcType = JdbcType.BIGINT),
            @Result(column = "create_time", property = "createTime", jdbcType = JdbcType.TIMESTAMP)
    })
    UserGoldCoinLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @UpdateProvider(type = UserGoldCoinLogSqlProvider.class, method = "updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserGoldCoinLog record, @Param("example") UserGoldCoinLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @UpdateProvider(type = UserGoldCoinLogSqlProvider.class, method = "updateByExample")
    int updateByExample(@Param("record") UserGoldCoinLog record, @Param("example") UserGoldCoinLogCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @UpdateProvider(type = UserGoldCoinLogSqlProvider.class, method = "updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserGoldCoinLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_gold_coin_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    @Update({
            "update t_user_gold_coin_log",
            "set user_id = #{userId,jdbcType=BIGINT},",
            "type = #{type,jdbcType=TINYINT},",
            "gold_coin = #{goldCoin,jdbcType=INTEGER},",
            "event_id = #{eventId,jdbcType=INTEGER},",
            "event_name = #{eventName,jdbcType=VARCHAR},",
            "event_target_id = #{eventTargetId,jdbcType=BIGINT},",
            "create_time = #{createTime,jdbcType=TIMESTAMP}",
            "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(UserGoldCoinLog record);
}