package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserSeasonRaceSummary;
import com.jusbilee.app.mybatis.pojo.UserSeasonRaceSummaryCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserSeasonRaceSummaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @SelectProvider(type=UserSeasonRaceSummarySqlProvider.class, method="countByExample")
    long countByExample(UserSeasonRaceSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @DeleteProvider(type=UserSeasonRaceSummarySqlProvider.class, method="deleteByExample")
    int deleteByExample(UserSeasonRaceSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Delete({
        "delete from t_user_season_race_summary",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Insert({
        "insert into t_user_season_race_summary (user_id, season_id, ",
        "win, loss, score, ",
        "is_deleted, create_time, ",
        "update_time)",
        "values (#{userId,jdbcType=BIGINT}, #{seasonId,jdbcType=INTEGER}, ",
        "#{win,jdbcType=INTEGER}, #{loss,jdbcType=INTEGER}, #{score,jdbcType=INTEGER}, ",
        "#{isDeleted,jdbcType=TINYINT}, #{createTime,jdbcType=TIMESTAMP}, ",
        "#{updateTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insert(UserSeasonRaceSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @InsertProvider(type=UserSeasonRaceSummarySqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Integer.class)
    int insertSelective(UserSeasonRaceSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @SelectProvider(type=UserSeasonRaceSummarySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="season_id", property="seasonId", jdbcType=JdbcType.INTEGER),
        @Result(column="win", property="win", jdbcType=JdbcType.INTEGER),
        @Result(column="loss", property="loss", jdbcType=JdbcType.INTEGER),
        @Result(column="score", property="score", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<UserSeasonRaceSummary> selectByExample(UserSeasonRaceSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Select({
        "select",
        "id, user_id, season_id, win, loss, score, is_deleted, create_time, update_time",
        "from t_user_season_race_summary",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="user_id", property="userId", jdbcType=JdbcType.BIGINT),
        @Result(column="season_id", property="seasonId", jdbcType=JdbcType.INTEGER),
        @Result(column="win", property="win", jdbcType=JdbcType.INTEGER),
        @Result(column="loss", property="loss", jdbcType=JdbcType.INTEGER),
        @Result(column="score", property="score", jdbcType=JdbcType.INTEGER),
        @Result(column="is_deleted", property="isDeleted", jdbcType=JdbcType.TINYINT),
        @Result(column="create_time", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_time", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    UserSeasonRaceSummary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @UpdateProvider(type=UserSeasonRaceSummarySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") UserSeasonRaceSummary record, @Param("example") UserSeasonRaceSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @UpdateProvider(type=UserSeasonRaceSummarySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") UserSeasonRaceSummary record, @Param("example") UserSeasonRaceSummaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @UpdateProvider(type=UserSeasonRaceSummarySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserSeasonRaceSummary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_season_race_summary
     *
     * @mbg.generated Wed Sep 14 07:56:40 CST 2016
     */
    @Update({
        "update t_user_season_race_summary",
        "set user_id = #{userId,jdbcType=BIGINT},",
          "season_id = #{seasonId,jdbcType=INTEGER},",
          "win = #{win,jdbcType=INTEGER},",
          "loss = #{loss,jdbcType=INTEGER},",
          "score = #{score,jdbcType=INTEGER},",
          "is_deleted = #{isDeleted,jdbcType=TINYINT},",
          "create_time = #{createTime,jdbcType=TIMESTAMP},",
          "update_time = #{updateTime,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserSeasonRaceSummary record);
}