package com.jusbilee.app.mybatis.dao;

import com.jusbilee.app.mybatis.pojo.UserStageLog;
import com.jusbilee.app.mybatis.pojo.UserStageLogCriteria;
import com.jusbilee.app.mybatis.pojo.UserStageLogCriteria.Criteria;
import com.jusbilee.app.mybatis.pojo.UserStageLogCriteria.Criterion;
import org.apache.ibatis.jdbc.SQL;

import java.util.List;
import java.util.Map;

public class UserStageLogSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String countByExample(UserStageLogCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("t_user_stage_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String deleteByExample(UserStageLogCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("t_user_stage_log");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String insertSelective(UserStageLog record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("t_user_stage_log");

        if (record.getUserId() != null) {
            sql.VALUES("user_id", "#{userId,jdbcType=BIGINT}");
        }

        if (record.getSongId() != null) {
            sql.VALUES("song_id", "#{songId,jdbcType=INTEGER}");
        }

        if (record.getStageSongId() != null) {
            sql.VALUES("stage_song_id", "#{stageSongId,jdbcType=INTEGER}");
        }

        if (record.getStageLevelId() != null) {
            sql.VALUES("stage_level_id", "#{stageLevelId,jdbcType=INTEGER}");
        }

        if (record.getIsAssist() != null) {
            sql.VALUES("is_assist", "#{isAssist,jdbcType=TINYINT}");
        }

        if (record.getAssistUserId() != null) {
            sql.VALUES("assist_user_id", "#{assistUserId,jdbcType=BIGINT}");
        }

        if (record.getScore() != null) {
            sql.VALUES("score", "#{score,jdbcType=INTEGER}");
        }

        if (record.getIsPassed() != null) {
            sql.VALUES("is_passed", "#{isPassed,jdbcType=TINYINT}");
        }

        if (record.getCreateTime() != null) {
            sql.VALUES("create_time", "#{createTime,jdbcType=TIMESTAMP}");
        }

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String selectByExample(UserStageLogCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("id");
        } else {
            sql.SELECT("id");
        }
        sql.SELECT("user_id");
        sql.SELECT("song_id");
        sql.SELECT("stage_song_id");
        sql.SELECT("stage_level_id");
        sql.SELECT("is_assist");
        sql.SELECT("assist_user_id");
        sql.SELECT("score");
        sql.SELECT("is_passed");
        sql.SELECT("create_time");
        sql.FROM("t_user_stage_log");
        applyWhere(sql, example, false);

        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }

        if (example.getLimit() != null && example.getOffset() != null) {
            StringBuilder buf = new StringBuilder(128);
            sql.usingAppender(buf);
            buf.append(" limit ");
            buf.append(example.getOffset());
            buf.append(", ");
            buf.append(example.getLimit());
            return buf.toString();
        }
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserStageLog record = (UserStageLog) parameter.get("record");
        UserStageLogCriteria example = (UserStageLogCriteria) parameter.get("example");

        SQL sql = new SQL();
        sql.UPDATE("t_user_stage_log");

        if (record.getId() != null) {
            sql.SET("id = #{record.id,jdbcType=BIGINT}");
        }

        if (record.getUserId() != null) {
            sql.SET("user_id = #{record.userId,jdbcType=BIGINT}");
        }

        if (record.getSongId() != null) {
            sql.SET("song_id = #{record.songId,jdbcType=INTEGER}");
        }

        if (record.getStageSongId() != null) {
            sql.SET("stage_song_id = #{record.stageSongId,jdbcType=INTEGER}");
        }

        if (record.getStageLevelId() != null) {
            sql.SET("stage_level_id = #{record.stageLevelId,jdbcType=INTEGER}");
        }

        if (record.getIsAssist() != null) {
            sql.SET("is_assist = #{record.isAssist,jdbcType=TINYINT}");
        }

        if (record.getAssistUserId() != null) {
            sql.SET("assist_user_id = #{record.assistUserId,jdbcType=BIGINT}");
        }

        if (record.getScore() != null) {
            sql.SET("score = #{record.score,jdbcType=INTEGER}");
        }

        if (record.getIsPassed() != null) {
            sql.SET("is_passed = #{record.isPassed,jdbcType=TINYINT}");
        }

        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");
        }

        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("t_user_stage_log");

        sql.SET("id = #{record.id,jdbcType=BIGINT}");
        sql.SET("user_id = #{record.userId,jdbcType=BIGINT}");
        sql.SET("song_id = #{record.songId,jdbcType=INTEGER}");
        sql.SET("stage_song_id = #{record.stageSongId,jdbcType=INTEGER}");
        sql.SET("stage_level_id = #{record.stageLevelId,jdbcType=INTEGER}");
        sql.SET("is_assist = #{record.isAssist,jdbcType=TINYINT}");
        sql.SET("assist_user_id = #{record.assistUserId,jdbcType=BIGINT}");
        sql.SET("score = #{record.score,jdbcType=INTEGER}");
        sql.SET("is_passed = #{record.isPassed,jdbcType=TINYINT}");
        sql.SET("create_time = #{record.createTime,jdbcType=TIMESTAMP}");

        UserStageLogCriteria example = (UserStageLogCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    public String updateByPrimaryKeySelective(UserStageLog record) {
        SQL sql = new SQL();
        sql.UPDATE("t_user_stage_log");

        if (record.getUserId() != null) {
            sql.SET("user_id = #{userId,jdbcType=BIGINT}");
        }

        if (record.getSongId() != null) {
            sql.SET("song_id = #{songId,jdbcType=INTEGER}");
        }

        if (record.getStageSongId() != null) {
            sql.SET("stage_song_id = #{stageSongId,jdbcType=INTEGER}");
        }

        if (record.getStageLevelId() != null) {
            sql.SET("stage_level_id = #{stageLevelId,jdbcType=INTEGER}");
        }

        if (record.getIsAssist() != null) {
            sql.SET("is_assist = #{isAssist,jdbcType=TINYINT}");
        }

        if (record.getAssistUserId() != null) {
            sql.SET("assist_user_id = #{assistUserId,jdbcType=BIGINT}");
        }

        if (record.getScore() != null) {
            sql.SET("score = #{score,jdbcType=INTEGER}");
        }

        if (record.getIsPassed() != null) {
            sql.SET("is_passed = #{isPassed,jdbcType=TINYINT}");
        }

        if (record.getCreateTime() != null) {
            sql.SET("create_time = #{createTime,jdbcType=TIMESTAMP}");
        }

        sql.WHERE("id = #{id,jdbcType=BIGINT}");

        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_stage_log
     *
     * @mbg.generated Sat Sep 10 23:20:28 CST 2016
     */
    protected void applyWhere(SQL sql, UserStageLogCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }

        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }

        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }

                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }

                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }

        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}